### PR TITLE
Remove contributors.md file

### PR DESCRIPTION
**Pull request by ahuang11**
I think it's important to recognize our contributors!

### CODE REVIEW

**Comment by desertaxle** [comment]
I also think it's important to recognize contributors, but, to play devil's advocate, GitHub tracks contributors also. I think GitHub's display is more prominent and it gets tracked automatically. Does the CONTRIBUTORS.md file have an advantage over GitHub's contributors feature?

**Comment by ahuang11** [comment]
As I was creating this PR, I was also thinking of that, and was wondering the necessity of this file, or should we just do https://github.com/all-contributors/all-contributors

**Comment by desertaxle** [comment]
I'd opt for using native GitHub functionality along with specifically mentioning contributors in the notes for each release. I'd rather not add the overhead of another tool.

**Review by desertaxle — COMMENTED** [review]
I'd opt for using native GitHub functionality along with specifically mentioning contributors in the notes for each release. I'd rather not add the overhead of another tool. If that's the direction we decide to go, we should remove our CONTRIBUTORS.md file.

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
