### PR TITLE
Add checklist for release

### PR DESCRIPTION
**Pull request by ahuang11**

### CODE REVIEW

**Comment by ahuang11** [comment]
Add to catalog should be a release check

**Comment by desertaxle** [comment]
I believe we discussed making the release template a little more evergreen and referencing info in MAINTAINERS.md where appropriate.

**Review by desertaxle — COMMENTED** [review]
I believe we discussed making the release template a little more evergreen and referencing info in MAINTAINERS.md where appropriate.

**Comment by ahuang11** [comment]
Will replace this PR with an issue instead since this is stale.

**Pull request closed without merging**
